server:
  port: 8091

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: sbb
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB_NAME:grad_stepup}
    username: ${DB_USERNAME:bj_grad}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 50
      max-wait: 1000
      test-on-borrow: true
      initial-size: 5
      min-idle: 5
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  flyway:
    locations: classpath:db/migration
    enabled: true


security:
  jwt:
    secret: ${JWT_SECRET:_SEMS_JWT_SECRET_201708240805987}
    expiration-in-seconds: 600
